---
title: "missing-protein-unique-peptides"
output: html_document
date: "2023-04-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
```



Import peptides of identified missing proteins
```{r}
MP_final_peptide <- readxl::read_xlsx('missing-protein-project/data/details_298_proteins.xlsx', sheet = 2)
head(MP_final_peptide)
```

import uniqueness checking
```{r}
uniqueness_checking <- readxl::read_xlsx('missing-protein-project/data/details_298_proteins.xlsx', sheet = 3)
head(uniqueness_checking)
```




```{r}
MP_final_peptide$Source <- str_extract(MP_final_peptide$Source, '^IPAS[0-9]+(?=_)')
```

```{r}
MP_final_peptide$unique <- ifelse(is.na(MP_final_peptide$unique) | MP_final_peptide$unique == 'N', 0 , 1)
```


```{r}
MP_204_products <- read_csv('missing-protein-project/output/protein list/detected_204_MP_products.csv')
MP_204_products$IPAS <- paste0('IPAS', str_extract(MP_204_products$IPAS, '(?<=IP).+(?=_)'))
```


```{r}
unique_peptide_summary <- MP_final_peptide %>% filter(unique == 1) %>% group_by(Gene, Source) %>% summarise(n=n(), unique_peptide=paste0(peptide.seq, collapse = '+')) %>% arrange(Gene, desc(n), .by_group = FALSE) %>% ungroup()


```


```{r}
unique_peptide_summary <- MP_204_products %>% left_join(unique_peptide_summary, by=c('accession' = 'Gene', 'IPAS' = 'Source')) %>% replace_na(list(n=0))
write_csv(unique_peptide_summary, 'missing-protein-project/output/missing_protein_unique_peptides.csv')
```


# plot unique peptide frequency for MP  with/without RNA expression
```{r}
unique_peptide_summary <-  unique_peptide_summary %>% mutate(count_discrete=ifelse(n >= 50, '50+', n))
unique_peptide_summary$count_discrete <- factor(unique_peptide_summary$count_discrete, levels=c(as.character(0:49), '50+'))

unique_peptide_summary %>% 
  ggplot(aes(x=count_discrete)) +
  geom_bar(position = 'identity', fill='red') +
theme_bw() +
  xlab('Matched unique peptide counts') +
  ylab('Frequency') +
  ggtitle('Matched unique peptide frequency of identified 204 missing proteins products') +
  scale_x_discrete(breaks=c('0', seq(5, 49, 5), '50+'), drop=FALSE) +
  scale_y_continuous(limits=c(0, 75))
```


# plot unique peptide frequency for MP with RNA expression
```{r}
unique_peptide_summary <- unique_peptide_summary %>% filter(TPM > 0)
unique_peptide_summary <-  unique_peptide_summary %>% mutate(count_discrete=ifelse(n >= 50, '50+', n))
unique_peptide_summary$count_discrete <- factor(unique_peptide_summary$count_discrete, levels=c(as.character(0:49), '50+'))

unique_peptide_summary %>% 
  ggplot(aes(x=count_discrete)) +
  geom_bar(position = 'identity', fill='blue') +
theme_bw() +
  xlab('Matched unique peptide counts') +
  ylab('Frequency') +
  ggtitle('Matched unique peptide frequency of identified 119 missing proteins products 
          with mRNA expression') +
  scale_x_discrete(breaks=c('0', seq(5, 49, 5), '50+'), drop=FALSE) +
  scale_y_continuous(limits=c(0, 75))
```

