---
title: "connection between tce and primary cell"
output: html_document
date: "2022-11-03"
---



```{r}
library(tidyverse)
```


```{r}
gastric_nsaf <- read.csv('data/gastric_primary_cell/gastric_primary_cell_nsaf_2.csv', row.names = 1)
primary_cell_gastric_nsaf_vec <- rowSums(gastric_nsaf)
primary_cell_gastric_nsaf <- as_tibble(primary_cell_gastric_nsaf_vec, rownames = 'accession')
load('data/support data/TCE_annotation.rda')
```

```{r}
load('cache/missing_protein.rda')
# missing_protein_df <- missing_protein_df %>% filter(PE == 'Evidence at transcript level')
missing_proteins <- missing_protein_df %>% filter(PE != 'Uncertain') %>% select(`gene name(s)`) %>% pull
P1_5_proteins <- missing_protein_df  %>% select(`gene name(s)`) %>% pull

missing_proteins_accession <- missing_protein_df %>% filter(PE != 'Uncertain') %>% select(Accession) %>% pull
P1_5_proteins_accession <- missing_protein_df %>% select(Accession) %>% pull
```


```{r}
extract_sample_id <- function(x, disease) {
  rownames(x[x$disease %in% disease, ,drop=FALSE])
}
```


# section 1 data processing
```{r}
nasf_tce_tbl <- read.csv('data/cell line raw data/nasf_tce_2.csv', row.names = 1)
```


Breast         Colon       Gastric        Glioma      Leukemia     LungAdeno   Lymphoblast      Melanoma Neuroblastoma       Ovarian 
  39            10             9            10            14            60             2             5             2            14 
   Pancreatic      Prostate          SCLC (similar)
           18             5            27     
```{r}
# gastric_cell_line <- c('IP0986_1701', 'IP0987_1701', 'IP0988_1701',
#   'IP0989_1701', 'IP0991_1701', 'IP0992_1701', 'IP7101_1701', 'IP7129_1701', 'IP7128_1701')
tce_nasf <- nasf_tce_tbl %>% select(all_of(extract_sample_id(TCE_annotation, disease = 'Colon')
))
tce_nasf_mat <- as.matrix(tce_nasf)
tce_gastric_nasf <- rowSums(tce_nasf_mat)
tce_gastric_nasf <- as_tibble(tce_gastric_nasf, rownames = 'accession')
```



<!-- # lets try another cancer -->
<!-- IP0302_1701	Colon			 -->
<!-- IP0410_1701	Colon			 -->
<!-- IP0411_1701	Colon			 -->
<!-- IP0412_1701	Colon			 -->
<!-- IP0413_1701	Colon			 -->
<!-- IP0414_1701	Colon			 -->
<!-- IP0415_1701	Colon			 -->
<!-- IP0301_1701	Colon -->
<!-- ```{r} -->
<!-- colon_cell_line <- c('IP0302_1701', 'IP0410_1701', 'IP0411_1701', 'IP0412_1701', 'IP0413_1701', 'IP0414_1701', 'IP0415_1701', 'IP0301_1701') -->
<!-- tce_nasf <- nasf_tce_tbl %>% select(all_of(colon_cell_line)) -->
<!-- tce_nasf_mat <- as.matrix(tce_nasf) -->
<!-- tce_colon_nasf <- rowSums(tce_nasf_mat) -->
<!-- tce_colon_nasf <- as_tibble(tce_colon_nasf, rownames = 'accession') -->
<!-- tce_gastric_nasf  <- tce_colon_nasf -->
<!-- ``` -->



```{r}
dat <- full_join(primary_cell_gastric_nsaf, tce_gastric_nasf, by='accession') %>% replace(is.na(.), 0) 
colnames(dat) <- c('accession', 'primary_cell', 'TCE')
# remove case when two read are both 0
dat <- dat %>% filter(!(primary_cell == 0 & TCE == 0))
dat$primary_cell <- log(dat$primary_cell + 1)
dat$TCE <- log(dat$TCE + 1)

RP_dat <- dat %>% filter(!(accession %in% P1_5_proteins_accession))
RP_dat_filtered <- RP_dat %>% filter(!(primary_cell == 0 | TCE == 0))
```

```{r}
plt <- ggpubr::ggscatter(dat, x = 'primary_cell', y = 'TCE', size = 1.5, # Points color, shape and size
   title='Gastric TCE vs. primary cell with spearman correlation',
   subtitle='All proteins',
   xlab = 'Primary cell (Log2 TPM + 1)',
   ylab = 'Cell line TCE (Log2 NSAF + 1)',
   ) +
    theme(legend.text = element_text(size=10)) 

dens1 <- ggplot(dat, aes(x = primary_cell)) + 
  geom_density(alpha = 0.4, fill='blue') + 
  theme_void() + 
  theme(legend.position = "none")

dens2 <- ggplot(dat, aes(x = TCE)) + 
  geom_density(alpha = 0.4, fill='blue') + 
  theme_void() + 
  theme(legend.position = "none") + 
  coord_flip()

dens1 + patchwork::plot_spacer() + plt + dens2 +  patchwork::plot_layout(ncol = 2, nrow = 2, widths = c(4, 1), heights = c(1, 4))
```
```{r}
plt <- ggpubr::ggscatter(RP_dat_filtered, x = 'primary_cell', y = 'TCE', size = 1.5, # Points color, shape and size
   add = "reg.line",  # Add regressin line
   add.params = list(color = "blue", fill = "lightgray"), # Customize reg. line
   conf.int = TRUE, # Add confidence interval
   cor.coef = TRUE, # Add correlation coefficient. see ?stat_cor
   cor.coeff.args = list(method = "pearson", label.x.npc=0.8, label.sep = "\n",
                         label.y.npc = "bottom"),
   title='Gastric TCE vs. primary cell with Pearson correlation',
   subtitle='All proteins that detected in both dataset',
     xlab = 'Primary cell (Log2 TPM + 1)',
   ylab = 'Cell line TCE (Log2 NSAF + 1)',
   ) +
    theme(legend.text = element_text(size=10)) 

dens1 <- ggplot(RP_dat_filtered, aes(x = primary_cell)) + 
  geom_density(alpha = 0.4, fill='blue') + 
  theme_void() + 
  theme(legend.position = "none")

dens2 <- ggplot(RP_dat_filtered, aes(x = TCE)) + 
  geom_density(alpha = 0.4, fill='blue') + 
  theme_void() + 
  theme(legend.position = "none") + 
  coord_flip()

dens1 + patchwork::plot_spacer() + plt + dens2 +  patchwork::plot_layout(ncol = 2, nrow = 2, widths = c(4, 1), heights = c(1, 4))
```



```{r}
dat_missing <- dat %>% filter(accession %in% missing_proteins_accession) %>% filter(!(primary_cell == 0 & TCE == 0))
dat_missing_filter <- dat_missing %>% filter(!(primary_cell == 0 | TCE == 0))
```

```{r}
plt <- ggpubr::ggscatter(dat_missing, x = 'primary_cell', y = 'TCE', size = 1.5, # Points color, shape and size
   title='Gastric TCE vs. primary cell with spearman correlation',
   subtitle='All proteins',
   xlab = 'Primary cell (Log2 TPM + 1)',
   ylab = 'Cell line TCE (Log2 NSAF + 1)',
   ) +
    theme(legend.text = element_text(size=10)) 

dens1 <- ggplot(dat_missing, aes(x = primary_cell)) + 
  geom_density(alpha = 0.4, fill='blue') + 
  theme_void() + 
  theme(legend.position = "none")

dens2 <- ggplot(dat_missing, aes(x = TCE)) + 
  geom_density(alpha = 0.4, fill='blue') + 
  theme_void() + 
  theme(legend.position = "none") + 
  coord_flip()

dens1 + patchwork::plot_spacer() + plt + dens2 +  patchwork::plot_layout(ncol = 2, nrow = 2, widths = c(4, 1), heights = c(1, 4))
```


```{r}
plt <- ggpubr::ggscatter(dat_missing_filter, x = 'primary_cell', y = 'TCE', size = 1.5, # Points color, shape and size
   add = "reg.line",  # Add regressin line
   add.params = list(color = "blue", fill = "lightgray"), # Customize reg. line
   conf.int = TRUE, # Add confidence interval
   cor.coef = TRUE, # Add correlation coefficient. see ?stat_cor
   cor.coeff.args = list(method = "pearson", label.x.npc=0.8, label.sep = "\n",
                         label.y.npc = "bottom"),
   title='Gastric TCE vs. primary cell with pearson correlation',
   subtitle='All proteins',
   xlab = 'Primary cell (Log2 TPM + 1)',
   ylab = 'Cell line TCE (Log2 NSAF + 1)',
   ) +
    theme(legend.text = element_text(size=10)) 

dens1 <- ggplot(dat_missing_filter, aes(x = primary_cell)) + 
  geom_density(alpha = 0.4, fill='blue') + 
  theme_void() + 
  theme(legend.position = "none")

dens2 <- ggplot(dat_missing_filter, aes(x = TCE)) + 
  geom_density(alpha = 0.4, fill='blue') + 
  theme_void() + 
  theme(legend.position = "none") + 
  coord_flip()

dens1 + patchwork::plot_spacer() + plt + dens2 +  patchwork::plot_layout(ncol = 2, nrow = 2, widths = c(4, 1), heights = c(1, 4))
```