---
title: "analysis_plasma"
output: html_document
date: "2022-09-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(DEqMS)
library(tidyverse)
library(pheatmap)
```

# Reading data
```{r}
SpC_plasma <- read.csv("data/Plasma_SumTickNormalization.csv", row.names = 'Acession')
```


```{r}
disease <- str_extract(colnames(SpC_plasma), '.+(?=\\.IP)')
disease <- str_replace_all(disease, '[\\.]+', '_')
# IPAS <-  str_extract(colnames(SpC_plasma)[-1], 'IP.+[0-9]+')
IPAS_annotation_plasma <- data.frame(disease = disease, row.names = colnames(SpC_plasma))
# should I use Pediatric GVHD as control?
unique(disease)
```


```{r}
missing_protein_df <- readxl::read_xlsx('data/PE2-5.xlsx')
missing_protein_df <- missing_protein_df[-c(1:12), ]
```


# Analysis
```{r}
y <- SpC_List(SpC_plasma, IPAS_annotation_plasma, NA_substitution = 0, proteins_filter = missing_protein_df$Accession)
```

# no strong evidence against outliers
```{r}
basic_describe(y)
```

```{r}
plasma_res <- one_vs_all_test(y)
unique_DEPs <- unique(unlist(lapply(plasma_res, rownames)))
```




```{r}
plot_heat_map(y, upper_limit = 5, row_keep = unique_DEPs)
```

