---
title: "demographic_correlation_analysis"
output: html_document
date: "2023-04-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = 'missing-protein-project')
```


```{r}
library(tidyverse)
```


check current working directory
```{r}
getwd()
```




Load missing sample missing protein statistics 
```{r}
MP_stats <- read_csv('output/sample_MP_stats.csv', show_col_types = FALSE)
MP_stats
MP_stats$IPAS <- paste0('IPAS', str_extract(MP_stats$IPAS, '(?<=IP)[0-9]+(?=_)'))
MP_stats <- MP_stats %>% filter(case==1)
```

Load sample demographic information
```{r}
sample_demographic <- read_csv('data/support-data/sample_demographic_data.csv', show_col_types = FALSE)
colnames(sample_demographic)
sample_demographic
```

```{r}
sample_demographic <- sample_demographic %>% select(IPAS, `Tumor cell percentage in Ascites cells`, `Prognosis`, `Survival from ascites collection (month)`, `Response for chemotherapy after peritoneal metastasis`, `Race`, `AGE`, `SEX`)
```


# correlation analysis
```{r}
combined <- inner_join(sample_demographic, MP_stats, by='IPAS')
combined$per <- as.numeric(sub("%", "", combined$per))
combined$`Tumor cell percentage in Ascites cells` <- as.numeric(sub("%", "", combined$`Tumor cell percentage in Ascites cells`))
combined
combined[match(target, combined$IPAS), ]
```



```{r}
combined$`Response for chemotherapy after peritoneal metastasis` <- ifelse(combined$`Response for chemotherapy after peritoneal metastasis` %in% c('Non responder', 'Non treatment'), 'Non repsonder/treatment', combined$`Response for chemotherapy after peritoneal metastasis`)
```


```{r}
wilcox.test(`per` ~ `Response for chemotherapy after peritoneal metastasis`, data=combined, na.rm=TRUE, paired=FALSE, exact=FALSE, conf.int=TRUE)
wilcox.test(`per` ~ `Prognosis`, data=combined, na.rm=TRUE, paired=FALSE, exact=FALSE, conf.int=TRUE)
```




```{r}
library(corrplot)
library(psych)
combined_numeric <- combined %>% select('Tumor cell percentage in Ascites cells', 'Survival from ascites collection (month)', 'count', 'countT', 'per')
colnames(combined_numeric) <- c('Tumor cell\n percentage', 'Survival from\n collection', 'number of MPs\n with mRNA', 'total number\n of MPs', 'Perc of MPs\n with mRNA')
corr <- corr.test(combined_numeric, method="spearman")
# corrplot.mixed(corr$r, p.mat = corr_p$p, lower = 'number', upper='ellipse', tl.cex=0.7,
#                na.label.col='black',
#                mar=c(0,0,2,0), insig='p-value', title="Spearman's Correlation between numeric variables")

corrplot(corr$r, method='ellipse', type='upper', p.mat = corr_p$p, insig = 'p-value', sig.level=0.01, title="Spearman's Correlation between numeric variables", mar=c(0,0,2,0), tl.cex=0.7, diag = TRUE)
corrplot(corr$r, method='number', type='lower', title="Spearman's Correlation between numeric variables", mar=c(0,0,2,0),
      tl.cex=0.7, diag = TRUE)
```




```{r}
combined
```


# reorder based on the same sample ID in all analysis
```{r}
target <- c("IPAS0981", "IPAS0982", "IPAS0993", "IPAS0995", "IPAS0999", "IPAS7100", "IPAS7103", "IPAS7105")
combined_output <- combined[match(target, combined$IPAS), ]
colnames(combined_output) <- c('Sample', 'Tumor cell percentage (%)', 'Prognosis', 'Survival from collection (month)', 
                               'Response for chemotherapy after peritoneal metastasis',
                               'Race', 'Age', 'Sex', 'case', 'number of identified MPs with mRNA', 'total number of identified MPs', 'percentage of identified MPs with mRNA (%)')
# reorder columns
combined_output <- combined_output %>% select(c('Sample', 'Sex', 'Race', 'Age', 'Tumor cell percentage (%)', 'Response for chemotherapy after peritoneal metastasis',
                            'Prognosis', 'Survival from collection (month)', 'number of identified MPs with mRNA', 'total number of identified MPs', 'percentage of identified MPs with mRNA (%)'))
```


# Analysis of binary table
```{r}
prognosis_summary <- combined_output %>% group_by(Prognosis) %>% summarize(
  `mean number of identified MPs with mRNA` = mean(`number of identified MPs with mRNA`),
  `mean total number of identified MPs`= mean(`total number of identified MPs`),
  `mean percentage of identifed MPs with mRNA (%)` = mean(`percentage of identified MPs with mRNA (%)`))


response_summary <- combined_output %>% group_by(`Response for chemotherapy after peritoneal metastasis`) %>% summarize(
  `mean number of identified MPs with mRNA` = mean(`number of identified MPs with mRNA`),
  `mean total number of identified MPs`= mean(`total number of identified MPs`),
  `mean percentage of identifed MPs with mRNA (%)` = mean(`percentage of identified MPs with mRNA (%)`))

# rbind(prognosis_summary, response_summary)
```





# Wilcox test between categorical variable and numberic values
```{r}
wilcox.test(`number of identified MPs with mRNA` ~ `Prognosis`, data=combined_output, na.rm=TRUE, paired=FALSE, exact=FALSE, conf.int=TRUE)
wilcox.test(`number of identified MPs with mRNA` ~ `Response for chemotherapy after peritoneal metastasis`, data=combined_output, na.rm=TRUE, paired=FALSE, exact=FALSE, conf.int=TRUE)

```




```{r}
wilcox.test(`total number of identified MPs` ~ `Prognosis`, data=combined_output, na.rm=TRUE, paired=FALSE, exact=FALSE, conf.int=TRUE)
wilcox.test(`total number of identified MPs` ~ `Response for chemotherapy after peritoneal metastasis`, data=combined_output, na.rm=TRUE, paired=FALSE, exact=FALSE, conf.int=TRUE)


```


```{r}
wilcox.test(`percentage of identified MPs with mRNA (%)` ~ `Prognosis`, data=combined_output, na.rm=TRUE, paired=FALSE, exact=FALSE, conf.int=TRUE)
wilcox.test(`percentage of identified MPs with mRNA (%)` ~ `Response for chemotherapy after peritoneal metastasis`, data=combined_output, na.rm=TRUE, paired=FALSE, exact=FALSE, conf.int=TRUE)
```


```{r}
wilcon_test <- t(matrix(c(0.2217, 0.0603, 0.233, 0.06675, 1, 0.09361), nrow = 3, ncol = 2))
rownames(wilcon_test) <- c('Response for chemotherapy', 'prognosis')
colnames(wilcon_test) <- c('number of MP with mRNA', 'total number of MP', 'perc of MP with mRNA(%)')
corrplot(wilcon_test, method='number', is.corr=FALSE)
```



```{r}
write_csv(combined_output, file = 'output/demographic_data.csv')
```

