---
title: "TCE_cancer_type_analysis"
output: html_document
date: "2022-11-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
nasf_TCE <- read.csv('data/nasf/nasf_TCE_missing_protein.csv', row.names = 1)
# nasf_TCE <- read.csv('data/cell line raw data//nasf_tce.csv', row.names = 1)
```

# import annotation
```{r}
IPAS_annotation <- read_csv('data/support data/IPAS_annotation.csv')
```

annotations
```{r}
create_annoataion <- function(data, annotation_table) {
  annotation_tbl <- annotation_table %>% select(ipas, disease) %>% filter(ipas %in% colnames(data))
  annotation_df <- data.frame(disease=annotation_tbl$disease)
  rownames(annotation_df) <- annotation_tbl$ipas
  return(annotation_df)
}

TCE_annotation <- create_annoataion(nasf_TCE, annotation_table = IPAS_annotation)
```


```{r}
table(TCE_annotation)
```

```{r}
extract_sample_id <- function(x, disease) {
  rownames(x$annotation[x$annotation$disease %in% disease, ,drop=FALSE])
}

# diseases_keep <- c('Colon', 'Glioma', 'Leukemia', 'Lymphoblast', 'Melanoma', 'Neuroblastoma', 'Prostate', 'Ovarian')
diseases_keep <- c('Breast', 'LungAdeno', 'Pancreatic', 'SCLC', 'Gastric')


SpC_list_TCE <- SpC_List(nasf_TCE, annotation = TCE_annotation)

replicates_for_keep <- extract_sample_id(SpC_list_TCE, diseases_keep)
```

```{r}
dat_TCE <- SpC_List(nasf_TCE, annotation = TCE_annotation, replicates_keep = replicates_for_keep)
dat_TCE$matrix <- dat_TCE$matrix[rowSums(dat_TCE$matrix) > 0, ]
```

```{r}
# basic_describe(dat_TCE)
```

```{r}
# breast_IPAS <- extract_sample_id(dat_TCE, 'Breast')
# SCLC_IPAS <- extract_sample_id(dat_TCE, 'SCLC')
# lungAdeno_IPAS <- extract_sample_id(dat_TCE, 'LungAdeno')
# pancreatic_IPAS <- extract_sample_id(dat_TCE, 'Pancreatic')
# gastric_IPAS <- extract_sample_id(dat_TCE, 'Gastric')
IPAS <- mapply(FUN=extract_sample_id, disease=c('Breast', 'SCLC', 'LungAdeno', 'Pancreatic', 'Gastric'), MoreArgs = list(x=dat_TCE))

# SpC_list_breast <-  SpC_List(nasf_TCE, annotation = TCE_annotation, replicates_keep = breast_IPAS)
# SpC_list_SCLC <-  SpC_List(nasf_TCE, annotation = TCE_annotation, replicates_keep = SCLC_IPAS)
# SpC_list_lungAdeno <-  SpC_List(nasf_TCE, annotation = TCE_annotation, replicates_keep = lungAdeno_IPAS)
# SpC_list_pancreatic <-  SpC_List(nasf_TCE, annotation = TCE_annotation, replicates_keep = pancreatic_IPAS)
# SpC_list_gastric <-  SpC_List(nasf_TCE, annotation = TCE_annotation, replicates_keep = gastric_IPAS)
SpC_lists <- mapply(FUN=SpC_List, replicates_keep=IPAS, MoreArgs = list(df=nasf_TCE, annotation=TCE_annotation), SIMPLIFY = FALSE)

```

```{r}
prefilter <- function(x) {
  N <- ncol(x$matrix)/10
  keep <- rowSums(x$matrix > 10000, na.rm = T) >= 2
  return(rownames(x$matrix[keep,]))
}

```



```{r}
# a <- prefilter(SpC_list_breast)
# b <- prefilter(SpC_list_SCLC)
# c <- prefilter(SpC_list_lungAdeno)
# d <- prefilter(SpC_list_pancreatic)
# e <- prefilter(SpC_list_gastric)
MPs <- lapply(SpC_lists, prefilter)
sapply(MPs, length)

```


```{r}
plot_venn_diagram(MPs)
```

